### ISSUE TITLE
ipv4的梯子能不能通过WARP实现ipv6出站？

### ISSUE THREAD

**Issue by lyangx77** [eastmaple/easytrojan#15]
最近小鸡被google墙了，每次都要验证就很烦。
然后我查了一下应该是能过通多warp添加ipv6，用ipv6访问google来解决这个问题。
但我不知道trojan怎么实现这个功能。大佬要是有时间能不能试一试？

**Comment by eastmaple** [comment]
请参考 https://github.com/eastmaple/easytrojan/issues/10
